site: Gesko
title: Gesko
greetings: Hello there! 👋
description: |
  Welcome to our website, your trusted source for up-to-date information and guidance across essential categories. In the **Finance and Investment** section, we provide in-depth insights into investment strategies, financial management, and tips to enhance your wealth.
  
  Meanwhile, our **Insurance** category explores various types of policies and how to choose the best coverage for your needs. We also offer valuable information in **Travel and Tourism**, featuring exciting destinations, travel tips, and accommodation recommendations to make your vacation experience even more enjoyable.

  In the **Health and Wellness** category, we present articles discussing healthy lifestyles, nutrition, and fitness tips to improve your quality of life. For tech enthusiasts, our **Technology and Gadgets** section showcases the latest reviews of innovative devices and cutting-edge technology developments.

  Additionally, we provide important information on **Law and Legal Consulting**, including your rights and legal advice for various situations. Finally, in the **Education** category, we offer guides and resources to help you achieve your academic and professional goals. Discover all this and more on our website!

lang: en-US
timezone:  America/New_York
repo: https://zonweb.github.io/the-best/ # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: gesko
  bio: just a minimalist, personal blog
  userpicture: 
  username: # general username
  github: DavideBri # github username
  twitter: # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: your-email@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://zonweb.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/the-best" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


